##===- lib/Mvm/CommonThread/Makefile -----------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../..

include $(LEVEL)/Makefile.config

MODULE_NAME = InlineMMTk

include $(LEVEL)/Makefile.common

