#===- ./Makefile -------------------------------------------*- Makefile -*--===#
# 
#                     The vmkit project
#===------------------------------------------------------------------------===#

LEVEL := ../..

MODULE=vmkit

include $(LEVEL)/Makefile.rules
