#===- ./Makefile -------------------------------------------*- Makefile -*--===#
# 
#                     The vmkit project
#===------------------------------------------------------------------------===#

LEVEL := ../../..

MODULE=openjdk

include $(LEVEL)/Makefile.rules
