##===- lib/JnJVM/LLVMRuntime/Makefile ----------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../..

include $(LEVEL)/Makefile.config

VMKIT_RUNTIME_IN=runtime-default.ll runtime-mmtk-thread.ll runtime-single.ll
VMKIT_RUNTIME_OUT=LLVMRuntime.inc

include $(LEVEL)/Makefile.common
