##===- lib/j3/ClassLib/GNUClasspath/Makefile ---------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../../..

include $(LEVEL)/Makefile.config

MODULE_WITH_GC=Classpath
INCLUDES+=-I../../VMCore -I..

include $(LEVEL)/Makefile.common

