##===- lib/j3/ClassLib/GNUClasspath/Makefile ---------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../../..

MODULE_WITH_GC=Classpath
INCLUDES+=-I$(PROJ_SRC_ROOT)/lib/j3/VMCore -I$(PROJ_SRC_ROOT)/lib/j3/ClassLib

include $(LEVEL)/Makefile.common

