##===- lib/vmkit/CommonThread/Makefile -----------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../..

MODULE_WITH_GC = CommonThread

include $(LEVEL)/Makefile.common

