##===- tools/llcj/libjnjvm/Makefile-------------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../..

include $(LEVEL)/Makefile.config

VMKIT_LIBRARYNAME = jnjvm
VMKIT_BUILD_ARCHIVE = 1
USEDLIBS = JnJVM.a Classpath.a Allocator.a CommonThread.a Mvm.a $(GCLIB).a

include $(LEVEL)/Makefile.common
