##===- mmtk/mmtk-alloc/Makefile ----------------------------*- Makefile -*-===##
#
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../..

MODULE=MMTKAlloc
NEED_BC=1

include $(LEVEL)/Makefile.common

