##===- mmtk/mmtk-alloc/Makefile ----------------------------*- Makefile -*-===##
#
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../..

include $(LEVEL)/Makefile.config

MODULE=MMTKAlloc
NEED_BC=1

CXX.Flags += -I$(PROJ_SRC_DIR)/../../lib/j3/VMCore

include $(LEVEL)/Makefile.common

