##===- lib/JnJVM/VMCore/Makefile ---------------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../..

include $(LEVEL)/Makefile.config

NO_PEDANTIC=1

ifeq ($(WITH_LLVM_GCC), 1)
  MODULE_NAME = P3
else
  LIBRARYNAME = P3
endif


include $(LEVEL)/Makefile.common

#CXX.Flags += 

