##===- lib/j3/ClassLib/Makefile ----------------------------*- Makefile -*-===##
#
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##
LEVEL = ../../..

EXTRA_DIST = ArrayCopy.inc \
             ClassContext.inc \
             ClasspathConstructor.inc \
             ClasspathField.inc \
             ClasspathMethod.inc \
             SetProperties.inc \
             Unsafe.inc

include $(LEVEL)/Makefile.config

DIRS = $(CLASSPATH_DIR)

include $(LEVEL)/Makefile.common
