##===- lib/J3/ClassLib/Makefile ----------------------------*- Makefile -*-===##
#
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##
LEVEL = ../../..

include $(LEVEL)/Makefile.config

DIRS = $(CLASSPATH_DIR)

include $(LEVEL)/Makefile.common
