##===- lib/vmkit/MMTk/Makefile -------------------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../..

MODULE_WITH_GC = MMTk

include $(LEVEL)/Makefile.common
