##===- lib/j3/Compiler/Makefile ----------------------------*- Makefile -*-===##
# 
#                     The VMKit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../..

include $(LEVEL)/Makefile.config

MODULE_WITH_GC = J3Compiler
INCLUDES+=-I../ClassLib/$(CLASSPATH_DIR) -I../ClassLib/ -I../VMCore -I../LLVMRuntime/$(BUILD_DIR)

include $(LEVEL)/Makefile.common
