##===- mmtk/magic/Makefile ---------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../..
LIBRARYNAME = MMTKRuntime
LOADABLE_MODULE = 1
USEDLIBS =

CXX.Flags += -I$(PROJ_OBJ_DIR)/../../lib/JnJVM/VMCore

include $(LEVEL)/Makefile.common

