##===- lib/Mvm/CommonThread/Makefile -----------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../..

EXTRA_DIST = Sigsegv-linux-x64.inc Sigsegv-macos-x64.inc

include $(LEVEL)/Makefile.config

MODULE_WITH_GC = CommonThread

include $(LEVEL)/Makefile.common

