##===- lib/vmkit/StaticGCPass/Makefile -----------------------*- Makefile -*-===##
#
#                            The VMKit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../..

NO_PREPARE_CODE=1
LIBRARY=vmkit-prepare-code

include $(LEVEL)/Makefile.rules

