##===- lib/JnJVM/VMCore/Makefile ---------------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../..

LIBRARYNAME = BoehmGC
include $(LEVEL)/Makefile.common

