##===- mmtk/mmtk-j3/Makefile -------------------------------*- Makefile -*-===##
#
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../..

include $(LEVEL)/Makefile.config

LIBRARYNAME = MMTKFake
LOADABLE_MODULE = 1
USEDLIBS =

CXX.Flags += -I$(PROJ_SRC_DIR)/../../lib/J3/VMCore

include $(LEVEL)/Makefile.common

