LEVEL := ..
DACAPO_VERSION := 9.12-bach
DACAPO_ARGS := -s default
DECAPO_BENCHMARKS := avrora batik eclipse fop h2 jython luindex lusearch pmd sunflow tomcat tradebeans tradesoap xalan

include ../Makefile.inc
