#===- ./Makefile -------------------------------------------*- Makefile -*--===#
# 
#                     The vmkit project
#===------------------------------------------------------------------------===#

LEVEL := ../..

DIRS := vm openjdk

include $(LEVEL)/Makefile.rules
