#===- ./Makefile -------------------------------------------*- Makefile -*--===#
# 
#                     The vmkit project
#===------------------------------------------------------------------------===#

LEVEL := ../..

PARALLEL_DIRS := vm openjdk

include $(LEVEL)/Makefile.rules
