LEVEL := ..
DACAPO_VERSION := 2006-10-MR2
DACAPO_ARGS := -s default
DECAPO_BENCHMARKS := antlr bloat chart eclipse fop hsqldb jython luindex lusearch pmd xalan
#DECAPO_BENCHMARKS := antlr bloat chart eclipse fop hsqldb jython luindex lusearch pmd xalan batik ps

include ../Makefile.inc
