#===- ./Makefile -------------------------------------------*- Makefile -*--===#
# 
#                     The vmkit project
#===------------------------------------------------------------------------===#

LEVEL := ../..

LIBS := vmkit j3 openjdk
TOOL := j3

include $(LEVEL)/Makefile.rules
