##===- lib/Mvm/Runtime/Makefile ----------------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../..

include $(LEVEL)/Makefile.config

LIBRARYNAME = Mvm
VMKIT_RUNTIME = LLVMRuntime.ll
BUILT_SOURCES = LLVMRuntime.inc

include $(LEVEL)/Makefile.common
