#===- ./Makefile -------------------------------------------*- Makefile -*--===#
# 
#                     The vmkit project
#===------------------------------------------------------------------------===#

LEVEL := ..

DIRS := vmkit j3

include $(LEVEL)/Makefile.rules
