#===- ./Makefile -------------------------------------------*- Makefile -*--===#
# 
#                     The vmkit project
#===------------------------------------------------------------------------===#

LEVEL := ../..

NO_PREPARE_CODE=1
LIBS := 
TOOL := vmkit-extract

include $(LEVEL)/Makefile.rules
