#===- ./Makefile -------------------------------------------*- Makefile -*--===#
# 
#                     The vmkit project
#===------------------------------------------------------------------------===#

LEVEL := ../..

LIBS := 
TOOL := vmkit-extract

include $(LEVEL)/Makefile.rules
