##===- lib/vmkit/Runtime/Makefile ----------------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../..

include $(LEVEL)/Makefile.config

MODULE_WITH_GC = VmkitCompiler

VMKIT_RUNTIME_IN=$(PROJ_SRC_DIR)/LLVMRuntime.ll
VMKIT_RUNTIME_OUT=LLVMRuntime.inc

include $(LEVEL)/Makefile.common
