##===- tools/vmjc/Makefile ---------------------------------*- Makefile -*-===##
# 
#                     The VMKit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../..

TOOL=vmjc
LINK_USE=J3Compiler J3 Classpath Vmkit VmkitCompiler MMTk CommonThread

include $(LEVEL)/Makefile.common
