##===- tools/vmjc/Makefile ---------------------------------*- Makefile -*-===##
# 
#                     The VMKit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../..

TOOL=vmjc
USE=J3 Classpath J3Compiler Vmkit VmkitCompiler MMTk CommonThread

include $(LEVEL)/Makefile.common
