##===- tools/testAllocator/Makefile ------------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../..

TOOLNAME = testAllocator
USEDLIBS = Allocator

include $(LEVEL)/Makefile.common

CXX.Flags += -I$(LEVEL)/lib/Mvm/Allocator
