##===- lib/N3/PNetLib/Makefile -----------------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../..

LIBRARYNAME = PNetLib
include $(LEVEL)/Makefile.common
CXX.Flags += -I../VMCore
