##===- lib/Mvm/GCMmap2/Makefile ----------------------------*- Makefile -*-===##
# 
#                     The vmkit project
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../..

LIBRARYNAME = GCMmap2
include $(LEVEL)/Makefile.common

CXX.Flags += -I../CommonThread -I../Allocator
